source:
  adapter:
    # 目前仅支持CAI框架登录
    type: cai
    # 【必修改】QQ号
    account: 1234567890
    # 【必修改】QQ密码
    password: abc123456
    # 在以下几个协议中选择：ANDROID_PAD, ANDROID_PHONE, ANDROID_WATCH, IPAD, MACOS
    # 若当前协议登录失败，请删除bot/目录所有文件，到此更换协议后重启bot
    # 重复此操作直到登录成功
    protocol: ANDROID_PAD
content:
  adapter:
    # 目前仅支持使用ChatGPT逆向库
    type: revChatGPT
    # 【必修改】ChatGPT网页版的access_token
    # 在浏览器登录ChatGPT后访问https://chat.openai.com/api/auth/session
    # 复制ey开头的access_token到这里
    access_token: eyxxxxxxxxxxxxxxx
