source:
  adapter:
    type: cai
    account: 1234567890
    password: abc123456
    protocol: ANDROID_PAD  # ANDROID_PAD, ANDROID_PHONE, ANDROID_WATCH, IPAD, MACOS
content:
  adapter:
    type: revChatGPT
    access_token: eyxxxxxxxxxxxxxxx
