name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Verify commit message
      run: |
        if [[ $(git log -1 --pretty=%B) != Release* ]]; then
          echo "Commit message does not contain a valid release version."
          exit 1
        fi

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Create virtual environment
      run: python -m venv .venv

    - name: Activate virtual environment
      run: source .venv/bin/activate

    - name: Install requirements
      run: pip install -r requirements.txt

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build executable for Linux
      run: pyinstaller --onefile --name lightqchat --add-data "static:static" main.py

    - name: Tag and release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          lightqchat
        tag_name: ${{ github.ref }}
        body: ${{ github.event.head_commit.message }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
